### ISSUE TITLE
Publishing 0.2.0

### ISSUE THREAD

**Issue by mwgkgk** [ccheek21/fre#9]
`cargo install` still rocking that `0.1.0`. Just opening this in case you forgot to [publish it manually](https://doc.rust-lang.org/cargo/reference/publishing.html#publishing-a-new-version-of-an-existing-crate); If there's an actual reason to withhold `master` from crates.io I then apologize for inconvenience and this should be closed.

**Comment by ccheek21** [comment]
Whoops. Forgot that part. Should be published now. Thanks for letting me know!
